version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_CONNECTION_STRING=mongodb+srv://<your_connection_string>

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
